---
title: "EpiCompare Report"
author: "Sera Choi"
date: "14/12/2021"
output: html_document
params:
  peakfile: 
   value: x
  file_name: 
   value: x
  output_dir:
   value: "./"
  blacklist:
    value: x
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

EpiCompare compares different epigenetic datasets for benchmarking and quality control purposes. 

### Dataset summary

Summary of peak files 

```{r name, echo=FALSE}
n <- 1
for (name in params$file_name){
  print(paste0("File", n, ": ", name))
  n <- n + 1
}
```

## Peakfile information {.tabset}

### Summary 

```{r, echo=FALSE}
peak_info(peak_list = params$peakfile,
          file_names = params$file_name,
          blacklist = params$blacklist)
```

### Peak widths 

Peak width after removing blacklisted peaks. 

```{r, echo=FALSE}
# remove blacklist regions 
peaklist_blrm <- list()
for (sample in params$peakfile){
  peak_blacklist_removed <- IRanges::subsetByOverlaps(sample, params$blacklist, invert = TRUE)
  peaklist_blrm <- c(peaklist_blrm, peak_blacklist_removed)
}

peak_width <- list()
for (sample in peaklist_blrm){
  width <- list(GenomicRanges::width(sample))
  peak_width <- c(peak_width, width)
}

boxplot(peak_width, names = params$file_name, ylab="Width (bp)", log = "y")
```


## Overlapping Peaks {.tabset}

### Sample files

```{r, echo=FALSE, fig.width=7}
overlap_heatmap(peaklist = peaklist_blrm,
                namelist = params$file_name)
```

### Sample files + other ENCODE datasets

```{r, echo=FALSE, fig.width=7}
overlap_heatmap(peaklist = peaklist_blrm,
                namelist = params$file_name)
```




