#' Summary on fragments
#'
#' This function outputs a summary on fragments using metrics generated by Picard.
#' Provides the number of mapped fragments, duplication rate and number of unique fragments.
#'
#'
#' @param picard_list List of duplication metrics generated by Picard in data frame.
#' Data frames must be listed using `list()` even for one sample (see example below).
#' To import Picard duplication metrics (.txt file) into R, use `picard <- read.table("/path/to/picard/output", header = TRUE, fill = TRUE)`
#' @param namelist List of names in the same order as list of Picard outputs. Add multiple by `c()`
#'
#' @return A table summarizing metrics on fragments.
#' @export
#'
#' @examples
#' library(EpiCompare)
#' data(CnT_H3K27ac_picard) # load example picard output
#' fragment_info(picard_list = list(CnT_H3K27ac_picard),
#'               namelist = "CUT&Tag")
#'
fragment_info <- function(picard_list, namelist){
  # create empty lists
  Mapped_Fragments <- c()
  Duplication_Rate <- c()
  Unique_Fragments <- c()
  # from picard summary retrieve the three metrics and store in a list
  for(i in 1:length(picard_list)){
    Mapped_Fragments <- c(Mapped_Fragments, picard_list[[i]]$READ_PAIRS_EXAMINED[1])
    Duplication_Rate <- c(Duplication_Rate, round(picard_list[[i]]$PERCENT_DUPLICATION[1]*100, 2))
    unique <- ((1-picard_list[[i]]$PERCENT_DUPLICATION[1]))*picard_list[[i]]$READ_PAIRS_EXAMINED[1]
    Unique_Fragments <- c(Unique_Fragments, round(unique))
  }
  # create data frame of metrics
  df_metric <- data.frame(Mapped_Fragments, Duplication_Rate, Unique_Fragments)
  rownames(df_metric) <- namelist # set row names as sample names
  return(df_metric)
}
