#' Import narrow peaks
#'
#' Import \emph{narrowPeak} files generated by
#' \href{https://github.com/macs3-project/MACS}{\code{MACS}}.
#'
#' Example dataset from:
#'  \url{https://www.encodeproject.org/files/ENCFF044JNJ/}.
#'  See \link[EpiCompare]{encode_H3K27ac} for more details.
#'
#' @param path Path to local  \emph{narrowPeak} file or remote URL.
#' @param as_file Metadata describing each of the column names in
#' narrowPeak files. Provided by \href{https://www.encodeproject.org/}{ENCODE}.
#' @param extraCols What vector type to assign each of the extra columns to.
#'
#' @source \href{https://support.bioconductor.org/p/80535/#80537}{
#' Solution from Bioconductor forum}
#' @export
#' @importFrom dplyr %>% rename mutate
#' @importFrom tidyr separate
#' @importFrom stats setNames
#' @importFrom GenomicRanges makeGRangesFromDataFrame
#' @examples
#'# path <- file.path("https://www.encodeproject.org/files",
#'#                   "ENCFF044JNJ/@@download/ENCFF044JNJ.bed.gz")
#'
#' path <- EpiCompare::write_example_peaks(datasets="encode_H3K27ac")
#' peaks <- EpiCompare::import_narrowPeak(path=path)
import_narrowPeak <- function(path,
                              as_file = file.path(
                                "https://www.encodeproject.org/documents",
                                "948203bb-8eb2-42a2-8b12-1c10f356c998",
                                "@@download/attachment",
                                "narrowPeak.as"
                              ),
                              extraCols = c(signalValue = "numeric",
                                             pValue = "numeric",
                                             qValue = "numeric",
                                             peak = "integer")
                              ){
  V2 <- type <- NULL;
  requireNamespace("data.table")
  requireNamespace("rtracklayer")

  #### Parse column metadata ####
  f <- readLines(as_file)
  f <- f[!f %in% c("(",")")][-seq_len(2)]
  type_dict <- c("string"="character",
                 "char[1]"="character",
                 "uint"="integer",
                 "int"="integer",
                 "float"="numeric")
  meta <- data.table::fread(text = f,
                            header = FALSE) %>%
    tidyr::separate(col = "V1",
                    into = c("type","name"),
                    sep = " +") %>%
    dplyr::rename(info=V2) %>%
    dplyr::mutate(typer=type_dict[type])
  extraCols <- stats::setNames(meta$typer, meta$name)
  reserved <- c("chrom","name","score","strand","chromStart","chromEnd")
  extraCols <- extraCols[!names(extraCols) %in% reserved]
  #### check for header ####
  header <- readLines(path, n = 2)
  #### Import peak data ####
  if(grepl("seqnames",header[1])){
    peaks <- data.table::fread(path)
    peaks <- GenomicRanges::makeGRangesFromDataFrame(df = peaks,
                                                     keep.extra.columns = TRUE)
  } else {
    peaks <- rtracklayer::import.bed(con = path,
                                     extraCols = extraCols)
  }
  message(formatC(length(peaks), big.mark = ",")," peaks imported.")
  return(peaks)
}
